sudo: false
language: node_js
os:
  - linux
  - osx
  - windows
dist: xenial
addons:
  apt:
    packages:
      - libusb-1.0-0-dev
      - libudev-dev
      - yasm
  homebrew:
    packages:
      - yasm
node_js:
  - v8
  - v10
  - v12
cache:
  directories:
    - node_modules
    - '$HOME/.npm'
after_success: yarn testci
